language: python
python:
  - 3.9.0
services:
  postgresql
addons:
  postgresql: '9.5'

install:
  - pip install -q -r requirements.txt
  - cp contrib/env-sample .env

before_script:
  - psql -c "CREATE DATABASE testdb;" -U postgres

script:
  - flake8
  - pytest --cov=assembleiaproject

after_success:
  - codecov