# Generated by Django 3.2.12 on 2022-07-06 15:38

import assembleiaproject.gallery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20220622_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(upload_to=assembleiaproject.gallery.models.Image.album_directory_path),
        ),
    ]
